/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jddevaughnbrown' at '6/24/17 2:05 PM' with Gradle 2.14.1
 *
 * @author jddevaughnbrown, @date 6/24/17 2:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
